# Redirect HTTP to HTTPS
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: devops-http-redirect
  namespace: devops
spec:
  parentRefs:
  - name: devops-gateway
    sectionName: http
  hostnames:
  - api.devops.local
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301

---

# HTTPS routes only
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: devops-api-hostname-route
  namespace: devops
spec:
  parentRefs:
  - name: devops-gateway
    sectionName: https
  hostnames:
  - api.devops.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /devops/blue
    backendRefs:
    - name: devops-blue-clusterip
      port: 8111
    timeouts:
      request: 8s
  - matches:
    - path:
        type: PathPrefix
        value: /devops/yellow
    backendRefs:
    - name: devops-yellow-clusterip
      port: 8112
    timeouts:
      request: 8s