---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: devops-secret-blue
  namespace: devops
spec:
  encryptedData:
    devops-blue-html-text-one: AgA4M2Sh6gdgV5NNsMnJPl8pGu+MFV2CrWvObf7V58slbuoRGZmbkNscRwQe/HQbRlj5OYHHi1ESE2aZlstDekHml6uFkxYJ/Oyjmc5e/DVePBRMH/1VV1n3Q/Jdx+88OSRPIL53gyVhEwA7YPW1pEjHOKcII+T2+LuW/XHW3mK9U3M0GLLe6mHtpENScGV8gS++XWS4IIl74jhi79FJR4LZ0a5BxVMQgxqxDM9642pBigginujkniqV+cIDzzVo93EqhU+HzVBuIQ+aUgxe/EwSYAfyiWovLiFq4v0c9t4c7FgknWfsBsWxMCljabtspkymqZIQIKdL450kuJqhS40PpyezAj0QhmgReT42X2oz1yy02J7uTzbVHjIqwHWe+AS7x9EihLK8l/6PG3sh41mB5RhRQvHl+wEeL0X2HPGWVXyvC8ZFeMgWeQFxd5+zZc7iQQ5Nal5xnYupqa6pvZF3QyiBr6S71M1pWMx/vtKJhxULo992qTo9hb/8XvBE/JwD4HaUqHqs34iMHo9mRLrAyu/HtSbwF6JBbDO6AaY4yXWIAAlXJP4j4JcLALqIwUGuM4Q9V0ys1uI9QjDXzTJlHRgbLYebp8kUmooZTsJ7PU7TPT9gOIDm3nuc4eVI69Z8aAeoMgldfyIQApIHQbpMV9xjL81KdFQDA7dov6oOxT+p+6JTfAPRxYl7BNzMPxdouGKeQWM/bHDF1BKFxxD/LUSWaKtspWuRuedvrZ2Tel8mI14kgTzeBn1offjJ
    devops-blue-html-text-two: AgBIx7eJWApS1FTPCrN5E8T9avo8mNjIhTAP6fMRlAqsHOf4FHS9bCK0Xp7DaFPHkf8jKCvgg/qfSHBk7D3VrhPqs2K1G7jyJA8N+pTwbvHThhtt0AtWdu+sYqTQir+lwnXSeVxmyZQ9wFrKJo8AI+mU6X7mDycskjmy6k7KsaZRLhuRr8XDmnJBxp8jqcByHlND/Atr3LMPjXe5Em/++VNkCvUPzq67zbZrte1fikO1E0ZRjpCoZ4NzCyg3zwrLc/GZDLi0WJba4kNhSodnjkVjM/JZCivfwp8qM+2wqoiVcD1ScOX/MtfZDBHdpPTVcHkS5aNrjaLVxAjBbGUiUe/NVnIyBvjl1Lc/zXTyNy3x6qjQaWtGJRrff7QdjOiuf3xZvoklXPcmwN9JxPi2gnFNwkyOaKb4Ur4ey3D/rBclT2pNRc9b9gIF2hiSBlxR80nHvKIPWpDl0y2BNLQh+QgLWqAxjl+6rCvtXAdBKDRYUjtbpYlhsteZUogc9ikZucxDCqf2V82i3t7DlDvvjfePgtdDVqiGLPYIdwhQveu1nKK3mkeM86OpZZgOTz9y+AHskovQU/Um8n0Z7rHCDE6aJVJfl1T2elzoOOS67nIkCd8fu/FHpJeODQ9Za3fhd7e/74M5y9SpkgqLnTWW6bYLowFLUP6Qwn4YXHQp3hxfYCOZp7uFUviBNDWkgWC5HSa//z9/mx0TlXwo/sOeR3b5
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: devops-secret-blue
      namespace: devops
