---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secret
  namespace: devops
spec:
  encryptedData:
    my-config-file.yml: AgBCa+ar6u2IjiCWYK8xAYCEepuQULTx5cAbMwQpkgtP9kPO1vxBffGCWzwpiHKweQMnBlPEJCXauFpnmGcCBS5mWYRPP1qJkFF+u6z62FVFnsyCY5fbOrXBuZaVztQtty/1X7RtCLPKLdL8geMxZrpUR0ZiDGU4jOIPowq+6+NRjG/Xy2veg4OK/3Il3N4UjyCBDMkeawiR0Gfqh/zNrqsOwBtp0ws8EjpJ79fij61bANVeUoFE3UqgidM2ZNhaCjiIDd2MDIuV7sgNaROpz9GRlcOZ1L9u4956sbPE2AcHFG6/gYqpwOzBb7cFuGIL5fGtismBgRjB2hNiLlnJd0weYCPS3fuEyGwGAa9tPL83yqMukHNaxhp0hpGZEi66qwtlqyNudR3KVQjiB5KIfayFfA+ZjTB52v4XpnPM0hEgd2Cc0mWHg+9HyezHMl/IYttPAme94lL5k3q4CODY5yTmXsFIGePZtSY40/Jr7K4An9awOiTmyUsrnoMerEFCQABCHscOWo0xK/x/A2ozLO9FmSQPuFTQHOxYtG8KXoza0eIXGUPhmWSPFl/N/2SB93iBwRu4jV8R98RHJv2eDb4CB1JO5HZIEIbNE9bEmGLnTudNcRl2WATlEUcqRDJF8IGXiMSUKDtcF+Hh+BXGKXpLDUURcd4yt37yWJ5ZNGU2jUjvatBucHO9TOhwUjg3KayuEXnYEE8HLDS+EOe4hDYuFyJhtSbPngK9KG7hmOA8ZGrcqe8Y6GJkV6pUEXS+9oTDaIMNxD02wx3M4xJ4pyMiND2ViaCC/F0P42IIeJsAJg9BHjCtSRye1u+OoaGQOvBy2ykj7dob/7w=
  template:
    metadata:
      name: my-secret
      namespace: devops
